# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [16]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint
# Import API key
from api_keys import g_key
gmaps.configure(api_key = g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [17]:
weather_data = '../output_data/CityWeatherData.csv'
weather_df = pd.read_csv(weather_data)
weather_df

,City,Country,Cloudiness,Date,Humidity,Lat,Lng,Max Temp,Windspeed
0,thompson,CA,90,1619893274,86.0,55.7435,-97.8558,21.20,9.22
1,rikitea,PF,88,1619893359,79.0,-23.1203,-134.9692,76.48,11.03
2,kavaratti,IN,11,1619893169,71.0,10.5669,72.6420,85.55,6.08
3,pangnirtung,CA,75,1619893360,57.0,66.1451,-65.7125,44.60,9.22
4,guiratinga,BR,46,1619893360,46.0,-16.3494,-53.7583,86.97,9.22
...,...,...,...,...,...,...,...,...,...
513,svetlaya,RU,91,1619893521,81.0,46.5389,138.3297,39.60,5.61
514,nador,MA,0,1619893521,48.0,35.1740,-2.9287,62.60,14.97
515,grand-santi,GF,47,1619893522,90.0,4.2500,-54.3833,80.15,4.23
516,kidal,ML,0,1619893522,9.0,18.4411,1.4078,99.54,7.29
517,umba,RU,41,1619893522,79.0,66.6871,34.3429,27.70,3.04

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [18]:
gmaps.configure(api_key = g_key)

In [19]:
locations = weather_df[['Lat','Lng']]

humidity = weather_df['Humidity'].astype(float)

fig = gmaps.figure()
heatmap_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, point_radius=1, max_intensity=100)

fig.add_layer(heatmap_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [20]:

max_temp = (weather_df["Max Temp"] <= 80) & (weather_df["Max Temp"] > 70)
wind_speed = weather_df["Windspeed"] < 10
cloudiness = weather_df["Cloudiness"] == 0

weather_df_best=weather_df[max_temp & wind_speed & cloudiness]

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [21]:
hotel_df = pd.DataFrame(weather_df_best, columns = ["City", "Country", "Lat", "Lng"])
hotel_df['Hotel Name'] = ""
hotel_df

               City Country      Lat       Lng Hotel Name
54   saint-philippe      RE -21.3585   55.7679
57     saint-pierre      RE -21.3393   55.4781
67          tucuman      AR -26.8241  -65.2226
84            pisco      PE -13.7000  -76.2167
160         nanning      CN  22.8167  108.3167
216            taft      IR  31.7471   54.2088
223    forquilhinha      BR -28.7475  -49.4722
319          zhuhai      CN  22.2769  113.5678
366      saint-paul      RE -21.0096   55.2707
448    saint-joseph      RE -21.3667   55.6167
457       gaziantep      TR  37.0594   37.3825

In [22]:
#Set parameters to search for hotels with 5000 meters.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?"

params = {"type" : "hotel",
          "keyword" : "hotel",
          "radius" : 5000,
          "key" : g_key}

for index,row in hotel_df.iterrows():
    lat = row['Lat']
    lng = row['Lng']
    city_name = row['City']
    params['location'] = f"{lat},{lng}"
    
    print(f"Retrieving hotels for Index {index}: {city_name}.")
    response = requests.get(base_url, params=params).json()
    results = response['results']
    
#incase the city does not have a hotel in the radius    
    try:
        print(f"Closest hotel in {city_name} is {results[0]['name']}.")
        hotel_df.loc[index, "Hotel Name"] = results[0]['name']
    except (KeyError, IndexError):
        print("Could not find result")
        print("-------------------------")
        
        
hotel_df

Retrieving hotels for Index 54: saint-philippe.
Closest hotel in saint-philippe is Les Embruns Du Baril.
Retrieving hotels for Index 57: saint-pierre.
Closest hotel in saint-pierre is Villa Delisle, Hotel & Spa.
Retrieving hotels for Index 67: tucuman.
Closest hotel in tucuman is Sheraton Tucuman Hotel.
Retrieving hotels for Index 84: pisco.
Closest hotel in pisco is HOSTAL MIRAMAR.
Retrieving hotels for Index 160: nanning.
Closest hotel in nanning is Yongjiang Hotel.
Retrieving hotels for Index 216: taft.
Closest hotel in taft is Do Sarv Taft Traditional Hotel.
Retrieving hotels for Index 223: forquilhinha.
Closest hotel in forquilhinha is Oma Zita Hotel.
Retrieving hotels for Index 319: zhuhai.
Closest hotel in zhuhai is Pullman Zhuhai.
Retrieving hotels for Index 366: saint-paul.
Closest hotel in saint-paul is HÃ´tel & Spa Le Saint Alexis.
Retrieving hotels for Index 448: saint-joseph.
Closest hotel in saint-joseph is "Plantation Bed and Breakfast.
Retrieving hotels for Index 457: gaziantep.
Closest hotel in gaziantep is Divan Gaziantep Otel.

               City Country      Lat       Lng                      Hotel Name
54   saint-philippe      RE -21.3585   55.7679            Les Embruns Du Baril
57     saint-pierre      RE -21.3393   55.4781      Villa Delisle, Hotel & Spa
67          tucuman      AR -26.8241  -65.2226          Sheraton Tucuman Hotel
84            pisco      PE -13.7000  -76.2167                  HOSTAL MIRAMAR
160         nanning      CN  22.8167  108.3167                 Yongjiang Hotel
216            taft      IR  31.7471   54.2088  Do Sarv Taft Traditional Hotel
223    forquilhinha      BR -28.7475  -49.4722                  Oma Zita Hotel
319          zhuhai      CN  22.2769  113.5678                  Pullman Zhuhai
366      saint-paul      RE -21.0096   55.2707     HÃ´tel & Spa Le Saint Alexis
448    saint-joseph      RE -21.3667   55.6167   "Plantation Bed and Breakfast
457       gaziantep      TR  37.0594   37.3825            Divan Gaziantep Otel

In [23]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [26]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content = hotel_info)
fig.add_layer(markers)
# Display figure
fig

Figure(layout=FigureLayout(height='420px'))